blog/urls.py
from django.conf.urls import url
from .import views

app_name='blog'

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('users/', include('users.urls')),
    url('users/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('specifics/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('register/',views.register, name='register'),
    path('index/', views.index, name='index'),
#    path('specifics/<int:pk>/', views.DetailView.as_view(), name='detail'),
#    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <=now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser

#  class User(AbstractUser):
#    nickname= models.CharField(max_length=50, blank=True)
#    class Meta(AbstractUser.Meta):
#        pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields=("username","email")

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

# Create your views here.

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html',{'posts':posts})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

#def detail(request, question_id):   
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question': question})

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question':question})

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

users/views.py
#from django.http import HttpResponseRedirect
#from django.shortcuts import get_object_or_404, render
#from django.urls import reverse
#from django.views import generic
#from django.utils import timezone

#from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)

        #验证数据的合法性
        if form.is_valid():
            form.save()
            return redirect('/')
    else: #请求不是POST，第一次访问注册页，展示空表单
        form=RegisterForm()
    return render(request, 'users/register.html', context={'form':form})

def index(request):
    return render(request, 'users/index.html')

blog/templates/blog/base.html
<!doctype html>

{% load staticfiles %}

<html>
<head>

<title>欢迎来到我的站点</title>

<script>
    function myFunction()
    {
    document.getElementById("demo").innerHTML="<b><u>Hello, Stupid MAN！！</b></u>";
    }
</script>
    <!--引入BOOTSTRAP-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">

<style>
    body{
        padding:20px;
    }

    #datalist{
        border-collapse: collapse;                   
    }
    #datalist td,th{
        border:1px solid grey;
        text-align:center;
        padding:5px 10px;
    }

</style>
</head>


<body bgcolor="pink" text="blue">
    <h1 id="demo">欢迎来到我的主页</h1>
    <button type="button" onclick="myFunction()"><b>点击有惊喜</b></button>
    <p><i>版权所有&nbsp;&copy;&lt;2018-5-23&gt;&nbsp;TUTU0016</i></p>
        
    <!--可扩展块-->
    {% block postsheet%}
    {% endblock%}

    {% block pollslist%}
    {% endblock%}

</body>
</html>

blog/templates/blog/post_list.html
{%extends 'blog/base.html'%}

{% block postsheet%}
    <table id="datalist">
    <tr>
        <th>发布时间</th>
        <th>作者</th>
        <th>主题</th>
        <th>内容</th>
    </tr>
    {% for post in posts %}
    <tr>
        <td>{{post.published_date}}</td>
        <td>{{post.author}}</td>
        <td>{{post.title}}</td>
        <td>{{post.text|linebreaksbr}}</td>
    </tr>
    {% endfor %}
    </table>
    <br>
    <br>
    <a href="{% url 'polls:index' %}">访问投票页</a>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type='radio' name='choice' id="choice{{forloop.counter}}" value="{{choice.id}}" />
        <label for="choice{{forloop.counter}}">{{ choice.choice_text}}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{%extends 'blog/base.html'%}

{% load static %}
<!--因为使用了通用试图，这个样式表已经没用了-->
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{%block pollslist%}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <br>
    <br>
    <a href="{% url 'blog:post_list' %}">访问我的博客</a>
{%endblock%}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text}}--{{choice.votes}}vote{{ choice.votes|pluralize}}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'users:index' %}">Django Auth Example</a></h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default"><a href="{% url 'logout' %}?next={{request.path}}">注销登录</a>></button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{request.path}}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>注册</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h3>注册</h3>
                <form class="form" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">注册</button>
                </form>
                <div class="flex-center top-gap text-small">
                    <a href="login.html">已有账号登录</a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>